jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

specfile_path: aws-sam-cli.spec

actions:
  create-archive:
    - spectool --get-files --all ./aws-sam-cli.spec
    - bash -c "ls -1 aws-sam-*.tar.gz"
